repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/timothycrosley/isort
    rev: ''
    hooks:
      - id: isort
      
