version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

python:
  install:
      - method: pip
        path: .
      - requirements: docs/requirements.txt

sphinx:
  builder: html
  fail_on_warning: false
  configuration: docs/conf.py
