# -*- coding: utf-8 -*-
"""Catalog of every analysis form field.

Until Phase 3 slice 4 this was `AnalysisDashboards`, 198 lines in the frontend
-- 147 fields whose names the backend already wrote on its own (what each
`spec` reads, plus each runner's `PLOT_PARAMS`). Two hand-kept lists, in two
languages, with nothing checking that they agreed.

**Why declared and not derived.** The measurement that opened the slice: of the
147 fields, only 63 (43%) appear in a ROSS signature. The rest are not missing
by oversight -- they cannot come from any signature:

  * composition: `speed_min`/`speed_max`/`speed_steps` are three fields that
    become one `np.linspace` in the `speed_range` ROSS receives. There is no
    `speed_min` parameter in ROSS; it is an interface decision about how to ask
    a human for an array;
  * list editors: `probes`, `forces`, `unbalances`, `inps`;
  * presentation: `plot_type`, default units, conditional visibility (`deps`),
    slider bounds.

So the copy cannot go away -- and the way out is the same as `getEffectiveNodes`':
the rule is written on one side only, and tests cross this catalog against what
the runners read and against ROSS's real signatures (`tests/test_analysis_catalog.py`).

**`role`** says who consumes the field: `compute` (the runner's `spec` reads
it), `plot` (only `plot` reads it) or `interface` (neither -- the screen is the
consumer). Each runner's `PLOT_PARAMS` comes from here; it used to be a tuple
kept by hand in every file, and it was incomplete in seven of them: `probes`,
`inps` and `outs` are read in `plot` and did not appear on the list, which left
the cache guard not covering those fields.
"""


def A(id, label_en, label_pt, type, val, role, **extra):
    """Describe one analysis form field."""
    field = {
        "id": id,
        "label": {"en": label_en, "pt": label_pt},
        "type": type,
        "val": val,
        "role": role,
    }
    field.update(extra)
    return field


ANALYSES = {
    "campbell": [
        A(
            "speed_min",
            "Start Speed",
            "Velocidade Inicial",
            "range",
            0,
            "compute",
            min=0,
            max=1000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "speed_max",
            "End Speed",
            "Velocidade Final",
            "range",
            400,
            "compute",
            min=100,
            max=4000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "speed_steps",
            "Steps",
            "Passos",
            "range",
            50,
            "compute",
            min=10,
            max=200,
            step=1,
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "Default",
            "interface",
            options=["Default", "Mode Shape"],
        ),
        A(
            "frequencies",
            "Nº Frequencies",
            "Nº de Frequências",
            "number",
            6,
            "compute",
            adv="analysis",
            ross_param="frequencies",
        ),
        A(
            "frequency_type",
            "Freq. Type",
            "Tipo de Frequência",
            "select",
            "wd",
            "compute",
            options=["wd", "wn"],
            adv="analysis",
            ross_param="frequency_type",
        ),
        A(
            "torsional_analysis",
            "Torsional",
            "Torcional",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="torsional_analysis",
        ),
        # ROSS 3 (#1371): evaluate the frequency-dependent coefficients of each
        # mode at its own whirl frequency, iterated per speed, instead of at
        # the synchronous point. The analysis for subsynchronous stability.
        A(
            "matched_whirl",
            "Matched Whirl",
            "Whirl Ajustado",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="matched_whirl",
        ),
        A(
            "harmonics",
            "Harmonics [list]",
            "Harmônicos [lista]",
            "text",
            "[1]",
            "plot",
            adv="plot",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "RPM",
            "plot",
            options=["RPM", "rad/s"],
            adv="plot",
        ),
        A(
            "speed_units",
            "Speed Units",
            "Unidade de Velocidade",
            "select",
            "RPM",
            "plot",
            options=["RPM", "rad/s"],
            adv="plot",
        ),
        A(
            "damping_parameter",
            "Damping Param",
            "Parâm. de Amortecimento",
            "select",
            "log_dec",
            "plot",
            options=["log_dec", "damping_ratio"],
            adv="plot",
        ),
        A(
            "animation",
            "Animation",
            "Animação",
            "select",
            "False",
            "plot",
            options=["False", "True"],
            adv="plot",
            deps=["Mode Shape"],
            deps_de="plot_type",
        ),
    ],
    "ucs": [
        A(
            "k_min",
            "Min Stiffness (10^x N/m)",
            "Rigidez Mín. (10^x N/m)",
            "number",
            4,
            "compute",
        ),
        A(
            "k_max",
            "Max Stiffness (10^x N/m)",
            "Rigidez Máx. (10^x N/m)",
            "number",
            10,
            "compute",
        ),
        A(
            "num_modes",
            "Nº Modes",
            "Nº de Modos",
            "number",
            4,
            "compute",
            ross_param="num_modes",
        ),
        # ROSS takes one `bearing_speed_range`; the screen asks for two
        # numbers, the same interface decision the campbell makes with
        # `speed_min`/`speed_max`. Neither carries `ross_param`, because neither
        # is a ROSS argument -- together they compose one.
        #
        # The ids still say `freq`: ROSS 3 renamed the argument (the range sweeps
        # the rotor speed the bearing tables are tabulated on), the labels
        # followed, and the ids stayed because they are keys inside every
        # analysis the browser has already stored.
        #
        # Both born empty, and empty is the normal answer: with no range ROSS
        # derives one from the bearing itself, which is what every run of this
        # analysis did while the field was withdrawn. It was withdrawn because
        # ROSS raised on any value at all; commit 2a253e6 fixed that, and this
        # is the field coming back.
        A(
            "bearing_freq_min",
            "Bearing Speed Min",
            "Veloc. Mín. do Mancal",
            "number",
            "",
            "compute",
            adv="analysis",
        ),
        A(
            "bearing_freq_max",
            "Bearing Speed Max",
            "Veloc. Máx. do Mancal",
            "number",
            "",
            "compute",
            adv="analysis",
        ),
        A(
            "synchronous",
            "Synchronous",
            "Síncrono",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="synchronous",
        ),
        A(
            "stiffness_units",
            "Stiffness Units",
            "Unidade de Rigidez",
            "text",
            "N/m",
            "plot",
            adv="plot",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "rad/s",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
        ),
    ],
    "freq_response": [
        A(
            "speed_min",
            "Start Speed",
            "Velocidade Inicial",
            "range",
            0,
            "compute",
            min=0,
            max=1000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "speed_max",
            "End Speed",
            "Velocidade Final",
            "range",
            400,
            "compute",
            min=100,
            max=4000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "Default",
            "plot",
            options=["Default", "Magnitude", "Phase", "Polar Bode"],
        ),
        A(
            "inps",
            "Input Probes",
            "Sondas de Entrada",
            "probe_list",
            [{"node": 0, "dof": 0}],
            "plot",
        ),
        A(
            "outs",
            "Output Probes",
            "Sondas de Saída",
            "probe_list",
            [{"node": 0, "dof": 0}],
            "plot",
        ),
        A(
            "modes",
            "Modes [list]",
            "Modos [lista]",
            "text",
            "",
            "compute",
            adv="analysis",
            ross_param="modes",
        ),
        A(
            "free_free",
            "Free Free",
            "Livre-Livre",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="free_free",
        ),
        # ROSS 3 (#1371): hold the rotor at one speed and sweep Start/End Speed
        # as the excitation frequency. Empty keeps the synchronous sweep, where
        # the two are the same number -- and an empty field sends nothing, so
        # ROSS keeps its own default.
        A(
            "speed",
            "Rotor Speed (fixed)",
            "Velocidade do Rotor (fixa)",
            "number",
            "",
            "compute",
            default_unit="rad/s",
            adv="analysis",
            ross_param="speed",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "rad/s",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
        ),
        A(
            "amplitude_units",
            "Amplitude Units",
            "Unidade de Amplitude",
            "select",
            "m/N",
            "plot",
            options=["m/N", "mm/N", "microm/N", "m/(s*N)", "m/(s**2*N)"],
            adv="plot",
        ),
        A(
            "phase_units",
            "Phase Units",
            "Unidade de Fase",
            "select",
            "rad",
            "plot",
            options=["rad", "deg"],
            adv="plot",
            deps=["Default", "Phase", "Polar Bode"],
            deps_de="plot_type",
        ),
        A(
            "line_shape",
            "Line Shape",
            "Forma da Linha",
            "select",
            "linear",
            "plot",
            options=["linear", "log"],
            adv="plot",
            deps=["Magnitude"],
            deps_de="plot_type",
        ),
    ],
    "modes": [
        A(
            "speed",
            "Shaft Speed",
            "Velocidade do Eixo",
            "range",
            0,
            "compute",
            min=0,
            max=2000,
            step=10,
            default_unit="rad/s",
            ross_param="speed",
        ),
        A(
            "num_modes",
            "Nº Modes",
            "Nº de Modos",
            "number",
            12,
            "compute",
            ross_param="num_modes",
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "2D",
            "plot",
            options=["2D", "3D", "Orbit"],
        ),
        A("plot_idx", "Mode Index", "Índice do Modo", "number", 0, "plot"),
        A(
            "sparse",
            "Sparse",
            "Esparso",
            "select",
            "True",
            "compute",
            options=["True", "False"],
            adv="analysis",
            ross_param="sparse",
        ),
        A(
            "synchronous",
            "Synchronous",
            "Síncrono",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="synchronous",
        ),
        # ROSS 3 (#1371): the two ways of decoupling the whirl frequency from
        # the shaft speed. Mutually exclusive, and the runner says so by name.
        A(
            "frequency",
            "Whirl Frequency (fixed)",
            "Freq. de Whirl (fixa)",
            "number",
            "",
            "compute",
            default_unit="rad/s",
            adv="analysis",
            ross_param="frequency",
        ),
        A(
            "matched_whirl",
            "Matched Whirl",
            "Whirl Ajustado",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="matched_whirl",
        ),
        A(
            "orientation",
            "Orientation",
            "Orientação",
            "select",
            "major",
            "plot",
            options=["major", "x", "y"],
            adv="plot",
            deps=["2D"],
            deps_de="plot_type",
        ),
        A(
            "frequency_type",
            "Freq Type",
            "Tipo de Frequência",
            "select",
            "wd",
            "plot",
            options=["wd", "wn"],
            adv="plot",
            deps=["2D", "3D"],
            deps_de="plot_type",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "rad/s",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
            deps=["2D", "3D"],
            deps_de="plot_type",
        ),
        A(
            "damping_parameter",
            "Damping Param",
            "Parâm. de Amortecimento",
            "select",
            "log_dec",
            "plot",
            options=["log_dec", "damping_ratio"],
            adv="plot",
            deps=["2D", "3D"],
            deps_de="plot_type",
        ),
        A(
            "length_units",
            "Length Units",
            "Unidade de Comprimento",
            "select",
            "m",
            "plot",
            options=["m", "mm"],
            adv="plot",
            deps=["3D"],
            deps_de="plot_type",
        ),
        A(
            "phase_units",
            "Phase Units",
            "Unidade de Fase",
            "select",
            "rad",
            "plot",
            options=["rad", "deg"],
            adv="plot",
            deps=["3D"],
            deps_de="plot_type",
        ),
        A(
            "animation",
            "Animation",
            "Animação",
            "select",
            "False",
            "plot",
            options=["False", "True"],
            adv="plot",
            deps=["3D"],
            deps_de="plot_type",
        ),
        A(
            "nodes",
            "Nodes [list]",
            "Nós [lista]",
            "text",
            "",
            "plot",
            adv="plot",
            deps=["Orbit"],
            deps_de="plot_type",
        ),
    ],
    "unbalance": [
        A(
            "speed_min",
            "Start Speed",
            "Velocidade Inicial",
            "range",
            0,
            "compute",
            min=0,
            max=1000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "speed_max",
            "End Speed",
            "Velocidade Final",
            "range",
            400,
            "compute",
            min=100,
            max=4000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "Default",
            "plot",
            options=["Default", "Magnitude", "Phase", "Bode", "Polar Bode"],
        ),
        A(
            "unbalances",
            "Unbalance Excitations",
            "Excitações de Desbalanceamento",
            "unbalance_list",
            [{"node": 0, "mag": 0.01, "phase": 0}],
            "compute",
        ),
        A(
            "probes",
            "Measurement Probes",
            "Sondas de Medição",
            "angle_probe_list",
            [{"node": 0, "angle": 0}],
            "plot",
        ),
        A(
            "modes",
            "Modes [list]",
            "Modos [lista]",
            "text",
            "",
            "compute",
            adv="analysis",
            ross_param="modes",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "rad/s",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
        ),
        A(
            "amplitude_units",
            "Amplitude Units",
            "Unidade de Amplitude",
            "select",
            "m",
            "plot",
            options=["m", "mm", "microm"],
            adv="plot",
        ),
        A(
            "phase_units",
            "Phase Units",
            "Unidade de Fase",
            "select",
            "rad",
            "plot",
            options=["rad", "deg"],
            adv="plot",
            deps=["Default", "Phase", "Bode", "Polar Bode"],
            deps_de="plot_type",
        ),
        A(
            "line_shape",
            "Line Shape",
            "Forma da Linha",
            "select",
            "linear",
            "plot",
            options=["linear", "log"],
            adv="plot",
            deps=["Magnitude"],
            deps_de="plot_type",
        ),
    ],
    "time_response": [
        A(
            "speed",
            "Rot. Speed",
            "Velocidade de Rotação",
            "range",
            100,
            "compute",
            min=0,
            max=2000,
            step=10,
            default_unit="rad/s",
            ross_param="speed",
        ),
        A(
            "t_max",
            "Max Time (s)",
            "Tempo Máx. (s)",
            "number",
            1,
            "compute",
            min=0.1,
            max=10,
            step=0.1,
        ),
        A(
            "steps",
            "Time Steps",
            "Passos de Tempo",
            "number",
            1000,
            "compute",
            min=100,
            max=10000,
            step=100,
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "1D",
            "plot",
            options=["1D", "2D", "3D", "Frequency (DFFT)"],
        ),
        A(
            "forces",
            "Applied Forces F(t)",
            "Forças Aplicadas F(t)",
            "force_list",
            [{"node": 0, "dof": 0, "func": "1000 * np.cos(speed * t)"}],
            "compute",
        ),
        A(
            "probes",
            "Measurement Probes",
            "Sondas de Medição",
            "angle_probe_list",
            [{"node": 0, "angle": 0}],
            "plot",
        ),
        A(
            "method",
            "Integration Method",
            "Método de Integração",
            "select",
            "default",
            "compute",
            options=["default", "newmark"],
            adv="analysis",
            ross_param="method",
        ),
        A(
            "displacement_units",
            "Displacement Units",
            "Unidade de Deslocamento",
            "select",
            "m",
            "plot",
            options=["m", "mm", "microm"],
            adv="plot",
        ),
        A(
            "time_units",
            "Time Units",
            "Unidade de Tempo",
            "select",
            "s",
            "plot",
            options=["s", "min"],
            adv="plot",
            deps=["1D"],
            deps_de="plot_type",
        ),
        A(
            "rotor_length_units",
            "Rotor Len Units",
            "Unid. Compr. do Rotor",
            "select",
            "m",
            "plot",
            options=["m", "mm"],
            adv="plot",
            deps=["3D"],
            deps_de="plot_type",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "Hz",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
            deps=["Frequency (DFFT)"],
            deps_de="plot_type",
        ),
    ],
    "static": [
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "Free Body Diagram",
            "plot",
            options=[
                "Free Body Diagram",
                "Deformation",
                "Shearing Force",
                "Bending Moment",
            ],
        ),
        A(
            "deformation_units",
            "Deformation Units",
            "Unidade de Deformação",
            "select",
            "m",
            "plot",
            options=["m", "mm", "microm"],
            adv="plot",
            deps=["Deformation"],
            deps_de="plot_type",
        ),
        A(
            "rotor_length_units",
            "Rotor Len Units",
            "Unid. Compr. do Rotor",
            "select",
            "m",
            "plot",
            options=["m", "mm"],
            adv="plot",
        ),
        A(
            "force_units",
            "Force Units",
            "Unidade de Força",
            "text",
            "N",
            "plot",
            adv="plot",
            deps=["Free Body Diagram", "Shearing Force"],
            deps_de="plot_type",
        ),
        A(
            "moment_units",
            "Moment Units",
            "Unidade de Momento",
            "text",
            "N*m",
            "plot",
            adv="plot",
            deps=["Bending Moment"],
            deps_de="plot_type",
        ),
    ],
    "harmonic_balance": [
        A(
            "speed",
            "Speed",
            "Velocidade",
            "range",
            200,
            "compute",
            min=0,
            max=2000,
            step=10,
            default_unit="rad/s",
            ross_param="speed",
        ),
        A("t_initial", "Initial Time (s)", "Tempo Inicial (s)", "number", 0, "compute"),
        A("t_final", "Final Time (s)", "Tempo Final (s)", "number", 0.5, "compute"),
        A("t_steps", "Time Steps", "Passos de Tempo", "number", 1001, "compute"),
        A("hb_node", "Force Node", "Nó da Força", "number", 0, "compute"),
        A(
            "hb_magnitudes",
            "Magnitudes [list]",
            "Magnitudes [lista]",
            "text",
            "[2000]",
            "compute",
        ),
        A("hb_phases", "Phases [list]", "Fases [lista]", "text", "[0]", "compute"),
        A(
            "hb_harmonics",
            "Harmonics [list]",
            "Harmônicos [lista]",
            "text",
            "[1]",
            "compute",
        ),
        A(
            "probes",
            "Measurement Probes",
            "Sondas de Medição",
            "angle_probe_list",
            [{"node": 0, "angle": 0}],
            "plot",
        ),
        A(
            "gravity",
            "Gravity",
            "Gravidade",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="gravity",
        ),
        A(
            "n_harmonics",
            "Nº Harmonics",
            "Nº de Harmônicos",
            "number",
            1,
            "compute",
            adv="analysis",
            ross_param="n_harmonics",
        ),
        A(
            "amplitude_units",
            "Amplitude Units",
            "Unidade de Amplitude",
            "select",
            "m",
            "plot",
            options=["m", "mm", "microm"],
            adv="plot",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "Hz",
            "plot",
            options=["Hz", "RPM", "rad/s"],
            adv="plot",
        ),
    ],
    "clearance": [
        # Rebuilt twice. The first time, three fields became an unbalance table:
        # a single `node` box beside list-valued magnitude and phase could never
        # carry more than one value, and the one value it did carry reached
        # ROSS as a one-element array where a number was expected -- tolerated
        # by numpy until 2.5, an error after it.
        #
        # The second time the analysis itself changed. petrobras/ross#1377
        # rewrote `run_clearance_analysis` after API 617 (9th edition, 6.8.2.10
        # and 6.8.2.11): it sweeps a speed range from zero to trip, takes the
        # largest probe amplitude between the minimum allowable speed (Nma) and
        # the maximum continuous speed (Nmc), scales the response to the test
        # vibration limit and compares the scaled major axis at every element
        # carrying a `radial_clearance` with 75 % of the diametral clearance.
        # `speed`, `frequency` and `modes` left the signature; the range, the
        # two speeds and the probes entered it, and the unbalance became
        # optional -- blank, ROSS places the API 617 unbalance from the mode
        # shape; filled, the table overrides that placement.
        A(
            "speed_min",
            "Start Speed",
            "Velocidade Inicial",
            "range",
            0,
            "compute",
            min=0,
            max=1000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "speed_max",
            "End Speed (Trip)",
            "Velocidade Final (Trip)",
            "range",
            1000,
            "compute",
            min=100,
            max=4000,
            step=10,
            default_unit="rad/s",
        ),
        A(
            "minimum_allowable_speed",
            "Min. Allowable Speed (Nma)",
            "Velocidade Mínima Admissível (Nma)",
            "number",
            500,
            "compute",
            default_unit="rad/s",
            ross_param="minimum_allowable_speed",
        ),
        A(
            "maximum_continuous_speed",
            "Max. Continuous Speed (Nmc)",
            "Velocidade Máxima Contínua (Nmc)",
            "number",
            800,
            "compute",
            default_unit="rad/s",
            ross_param="maximum_continuous_speed",
        ),
        # The probes take part in the computation here, not only in the
        # drawing: Amax -- and with it the scale factor -- is read off them.
        A(
            "probes",
            "Vibration Probes",
            "Sondas de Vibração",
            "angle_probe_list",
            [{"node": 0, "angle": 0}],
            "compute",
            ross_param="probes",
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "Default",
            "plot",
            options=["Default", "Response", "Probe Response"],
        ),
        A(
            "mode",
            "Forward Mode Index",
            "Índice do Modo Direto",
            "number",
            0,
            "compute",
            adv="analysis",
            ross_param="mode",
        ),
        # Born empty on purpose: with no row ROSS places the API 617 unbalance
        # itself, from the mode shape, which is what the standard asks for.
        A(
            "unbalances",
            "Unbalance Excitations (blank: API 617)",
            "Excitações de Desbalanceamento (vazio: API 617)",
            "unbalance_list",
            [],
            "compute",
            adv="analysis",
        ),
        A(
            "speed_steps",
            "Speed Steps",
            "Passos de Velocidade",
            "number",
            101,
            "compute",
            adv="analysis",
        ),
        A(
            "num_modes",
            "Modes Computed",
            "Modos Calculados",
            "number",
            12,
            "compute",
            adv="analysis",
            ross_param="num_modes",
        ),
        A(
            "scale_factor_cap",
            "Scale Factor Cap (blank: none)",
            "Limite do Fator de Escala (vazio: nenhum)",
            "number",
            "",
            "compute",
            adv="analysis",
            ross_param="scale_factor_cap",
        ),
        A(
            "length_units",
            "Length Units",
            "Unidade de Comprimento",
            "select",
            "um",
            "plot",
            options=["um", "mm", "m"],
            adv="plot",
        ),
        A(
            "speed_units",
            "Speed Units",
            "Unidade de Velocidade",
            "select",
            "RPM",
            "plot",
            options=["RPM", "rad/s", "Hz"],
            adv="plot",
            deps=["Response", "Probe Response"],
            deps_de="plot_type",
        ),
        A(
            "line_shape",
            "Line Shape",
            "Forma da Linha",
            "select",
            "spline",
            "plot",
            options=["spline", "linear"],
            adv="plot",
            deps=["Response", "Probe Response"],
            deps_de="plot_type",
        ),
    ],
    "misalignment": [
        A(
            "speed",
            "Speed",
            "Velocidade",
            "range",
            125.66,
            "compute",
            min=0,
            max=2000,
            step=10,
            default_unit="rad/s",
            ross_param="speed",
        ),
        A("t_initial", "Initial Time (s)", "Tempo Inicial (s)", "number", 0, "compute"),
        A("t_final", "Final Time (s)", "Tempo Final (s)", "number", 0.5, "compute"),
        A("t_steps", "Time Steps", "Passos de Tempo", "number", 5000, "compute"),
        A(
            "unbalances",
            "Unbalance Excitations",
            "Excitações de Desbalanceamento",
            "unbalance_list",
            [{"node": 0, "mag": 0.0005, "phase": -1.57}],
            "compute",
        ),
        A(
            "coupling",
            "Coupling",
            "Acoplamento",
            "select",
            "flex",
            "compute",
            options=["flex", "rigid"],
            ross_param="coupling",
        ),
        A(
            "n",
            "Shaft Element (n)",
            "Elemento de Eixo (n)",
            "number",
            0,
            "compute",
            adv="analysis",
        ),
        A(
            "mis_type",
            "Mis. Type",
            "Tipo de Desalinhamento",
            "select",
            "parallel",
            "compute",
            options=["parallel", "angular", "combined"],
            adv="analysis",
            deps=["flex"],
            deps_de="coupling",
        ),
        A(
            "mis_distance_x",
            "Mis. Dist. X (m)",
            "Dist. de Desalinh. X (m)",
            "text",
            "0",
            "compute",
            adv="analysis",
            deps=["flex"],
            deps_de="coupling",
        ),
        A(
            "mis_distance_y",
            "Mis. Dist. Y (m)",
            "Dist. de Desalinh. Y (m)",
            "text",
            "2e-4",
            "compute",
            adv="analysis",
            deps=["flex"],
            deps_de="coupling",
        ),
        A(
            "mis_angle",
            "Mis. Angle (rad)",
            "Âng. de Desalinh. (rad)",
            "text",
            "0",
            "compute",
            adv="analysis",
            deps=["flex"],
            deps_de="coupling",
        ),
        A(
            "radial_stiffness",
            "Radial Stiff.",
            "Rigidez Radial",
            "text",
            "1e6",
            "compute",
            adv="analysis",
            deps=["flex"],
            deps_de="coupling",
        ),
        A(
            "bending_stiffness",
            "Bending Stiff.",
            "Rigidez à Flexão",
            "text",
            "1e6",
            "compute",
            adv="analysis",
            deps=["flex"],
            deps_de="coupling",
        ),
        A(
            "mis_distance",
            "Mis. Distance (m)",
            "Dist. de Desalinhamento (m)",
            "text",
            "2e-4",
            "compute",
            adv="analysis",
            deps=["rigid"],
            deps_de="coupling",
        ),
        A(
            "input_torque",
            "Input Torque",
            "Torque de Entrada",
            "text",
            "0",
            "compute",
            adv="analysis",
        ),
        A(
            "load_torque",
            "Load Torque",
            "Torque de Carga",
            "text",
            "0",
            "compute",
            adv="analysis",
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "1D",
            "plot",
            options=["1D", "2D", "3D", "Frequency (DFFT)"],
        ),
        A(
            "probes",
            "Measurement Probes",
            "Sondas de Medição",
            "angle_probe_list",
            [{"node": 0, "angle": 0}],
            "plot",
        ),
        A(
            "displacement_units",
            "Displacement Units",
            "Unidade de Deslocamento",
            "select",
            "m",
            "plot",
            options=["m", "mm", "microm"],
            adv="plot",
        ),
        A(
            "time_units",
            "Time Units",
            "Unidade de Tempo",
            "select",
            "s",
            "plot",
            options=["s", "min"],
            adv="plot",
            deps=["1D"],
            deps_de="plot_type",
        ),
        A(
            "rotor_length_units",
            "Rotor Len Units",
            "Unid. Compr. do Rotor",
            "select",
            "m",
            "plot",
            options=["m", "mm"],
            adv="plot",
            deps=["3D"],
            deps_de="plot_type",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "Hz",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
            deps=["Frequency (DFFT)"],
            deps_de="plot_type",
        ),
    ],
    "rubbing": [
        A(
            "speed",
            "Speed",
            "Velocidade",
            "range",
            125.66,
            "compute",
            min=0,
            max=2000,
            step=10,
            default_unit="rad/s",
            ross_param="speed",
        ),
        A("t_initial", "Initial Time (s)", "Tempo Inicial (s)", "number", 0, "compute"),
        A("t_final", "Final Time (s)", "Tempo Final (s)", "number", 0.5, "compute"),
        A("t_steps", "Time Steps", "Passos de Tempo", "number", 5000, "compute"),
        A(
            "unbalances",
            "Unbalance Excitations",
            "Excitações de Desbalanceamento",
            "unbalance_list",
            [{"node": 0, "mag": 0.0005, "phase": -1.57}],
            "compute",
        ),
        A(
            "n",
            "Shaft Element (n)",
            "Elemento de Eixo (n)",
            "number",
            0,
            "compute",
            adv="analysis",
            ross_param="n",
        ),
        A(
            "distance",
            "Distance (m)",
            "Distância (m)",
            "text",
            "7.95e-5",
            "compute",
            adv="analysis",
            ross_param="distance",
        ),
        A(
            "contact_stiffness",
            "Contact Stiff.",
            "Rigidez de Contato",
            "text",
            "1.1e6",
            "compute",
            adv="analysis",
            ross_param="contact_stiffness",
        ),
        A(
            "contact_damping",
            "Contact Damp.",
            "Amortec. de Contato",
            "text",
            "40",
            "compute",
            adv="analysis",
            ross_param="contact_damping",
        ),
        A(
            "friction_coeff",
            "Friction Coeff.",
            "Coef. de Atrito",
            "text",
            "0.3",
            "compute",
            adv="analysis",
            ross_param="friction_coeff",
        ),
        A(
            "torque",
            "Torque",
            "Torque",
            "select",
            "False",
            "compute",
            options=["False", "True"],
            adv="analysis",
            ross_param="torque",
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "1D",
            "plot",
            options=["1D", "2D", "3D", "Frequency (DFFT)"],
        ),
        A(
            "probes",
            "Measurement Probes",
            "Sondas de Medição",
            "angle_probe_list",
            [{"node": 0, "angle": 0}],
            "plot",
        ),
        A(
            "displacement_units",
            "Displacement Units",
            "Unidade de Deslocamento",
            "select",
            "m",
            "plot",
            options=["m", "mm", "microm"],
            adv="plot",
        ),
        A(
            "time_units",
            "Time Units",
            "Unidade de Tempo",
            "select",
            "s",
            "plot",
            options=["s", "min"],
            adv="plot",
            deps=["1D"],
            deps_de="plot_type",
        ),
        A(
            "rotor_length_units",
            "Rotor Len Units",
            "Unid. Compr. do Rotor",
            "select",
            "m",
            "plot",
            options=["m", "mm"],
            adv="plot",
            deps=["3D"],
            deps_de="plot_type",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "Hz",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
            deps=["Frequency (DFFT)"],
            deps_de="plot_type",
        ),
    ],
    "crack": [
        A(
            "speed",
            "Speed",
            "Velocidade",
            "range",
            125.66,
            "compute",
            min=0,
            max=2000,
            step=10,
            default_unit="rad/s",
            ross_param="speed",
        ),
        A("t_initial", "Initial Time (s)", "Tempo Inicial (s)", "number", 0, "compute"),
        A("t_final", "Final Time (s)", "Tempo Final (s)", "number", 0.5, "compute"),
        A("t_steps", "Time Steps", "Passos de Tempo", "number", 5000, "compute"),
        A(
            "unbalances",
            "Unbalance Excitations",
            "Excitações de Desbalanceamento",
            "unbalance_list",
            [{"node": 0, "mag": 0.0005, "phase": -1.57}],
            "compute",
        ),
        A(
            "crack_model",
            "Crack Model",
            "Modelo de Trinca",
            "select",
            "Mayes",
            "compute",
            options=["Mayes", "Gasch", "Flex Open", "Flex Breathing"],
            ross_param="crack_model",
        ),
        A(
            "n",
            "Shaft Element (n)",
            "Elemento de Eixo (n)",
            "number",
            0,
            "compute",
            adv="analysis",
            ross_param="n",
        ),
        A(
            "depth_ratio",
            "Depth Ratio",
            "Razão de Profundidade",
            "text",
            "0.2",
            "compute",
            adv="analysis",
            ross_param="depth_ratio",
        ),
        A(
            "cross_divisions",
            "Cross Divisions",
            "Divisões Transversais",
            "text",
            "",
            "compute",
            adv="analysis",
            ross_param="cross_divisions",
        ),
        A(
            "plot_type",
            "Plot Type",
            "Tipo de Gráfico",
            "select",
            "1D",
            "plot",
            options=["1D", "2D", "3D", "Frequency (DFFT)"],
        ),
        A(
            "probes",
            "Measurement Probes",
            "Sondas de Medição",
            "angle_probe_list",
            [{"node": 0, "angle": 0}],
            "plot",
        ),
        A(
            "displacement_units",
            "Displacement Units",
            "Unidade de Deslocamento",
            "select",
            "m",
            "plot",
            options=["m", "mm", "microm"],
            adv="plot",
        ),
        A(
            "time_units",
            "Time Units",
            "Unidade de Tempo",
            "select",
            "s",
            "plot",
            options=["s", "min"],
            adv="plot",
            deps=["1D"],
            deps_de="plot_type",
        ),
        A(
            "rotor_length_units",
            "Rotor Len Units",
            "Unid. Compr. do Rotor",
            "select",
            "m",
            "plot",
            options=["m", "mm"],
            adv="plot",
            deps=["3D"],
            deps_de="plot_type",
        ),
        A(
            "frequency_units",
            "Freq. Units",
            "Unidade de Freq.",
            "select",
            "Hz",
            "plot",
            options=["RPM", "Hz", "rad/s"],
            adv="plot",
            deps=["Frequency (DFFT)"],
            deps_de="plot_type",
        ),
    ],
}


# Each analysis's title, which the screen uses in two places: the <select>
# options and the card header. Until the i18n slice these were two lists --
# one in index.html and a `typeNames` in the JS -- with the same twelve names
# typed by hand. Here it is one list, and a translated one.
TITLES = {
    "campbell": {"en": "Campbell Diagram", "pt": "Diagrama de Campbell"},
    "ucs": {"en": "UCS Diagram", "pt": "Diagrama UCS"},
    "freq_response": {"en": "Frequency Response", "pt": "Resposta em Frequência"},
    "modes": {"en": "Modal Analysis", "pt": "Análise Modal"},
    "unbalance": {"en": "Unbalance Response", "pt": "Resposta ao Desbalanceamento"},
    "time_response": {"en": "Time Response", "pt": "Resposta no Tempo"},
    "static": {"en": "Static Analysis", "pt": "Análise Estática"},
    "harmonic_balance": {"en": "Harmonic Balance", "pt": "Balanço Harmônico"},
    "clearance": {"en": "Clearance Analysis", "pt": "Análise de Folga"},
    "misalignment": {"en": "Misalignment Response", "pt": "Resposta a Desalinhamento"},
    "rubbing": {"en": "Rubbing Response", "pt": "Resposta a Roçamento"},
    "crack": {"en": "Crack Response", "pt": "Resposta a Trinca"},
}


def title(analysis, language="en"):
    names = TITLES.get(analysis)
    if not names:
        return analysis.upper()
    return names.get(language) or names["en"]


def titles(language="en"):
    return {name: title(name, language) for name in ANALYSES}


def fields(analysis, language="en"):
    """Return an analysis's fields, with the label already in the language asked."""
    output = []
    for field in ANALYSES.get(analysis, ()):
        copy_of = dict(field)
        copy_of["label"] = field["label"].get(language) or field["label"]["en"]
        output.append(copy_of)
    return output


def catalog(language="en"):
    """Return every analysis, ready to become JSON."""
    return {name: fields(name, language) for name in ANALYSES}


ROSS_METHOD = {
    "campbell": "run_campbell",
    "ucs": "run_ucs",
    "freq_response": "run_freq_response",
    "modes": "run_modal",
    "unbalance": "run_unbalance_response",
    "time_response": "run_time_response",
    "static": "run_static",
    "harmonic_balance": "run_harmonic_balance_response",
    "clearance": "run_clearance_analysis",
    "misalignment": "run_misalignment",
    "rubbing": "run_rubbing",
    "crack": "run_crack",
}


def default_params(analysis):
    """The values a card is born with -- and what the user sees first.

    Including the tables (probes, forces, unbalances): a card is born with one
    row in each, and sending `[]` instead measures something else. In the first
    version of the conversion probe I sent `[]`, and that produced two false
    results: `freq_response` blew up on all three models (the loop over
    input/output pairs did not run) and `time_response` came out "NO EFFECT" on
    both (with no force the response is zero, and zero is zero at any number of
    degrees of freedom).

    It lives here, and not in whoever needs it, because two callers need it now:
    the probe in `tools/` and the executable's self-test.
    """
    return {field["id"]: field.get("val") for field in ANALYSES[analysis]}


def plot_parameters(analysis):
    """Return the fields the computation may not read. Replaces PLOT_PARAMS.

    `interface` roles are included: Campbell's `plot_type` is this guard's
    original defect -- it took part in the computation without entering the
    cache key, so opening Mode Shape and going back to Default returned a
    15-point diagram with the form still saying 50.
    """
    return tuple(c["id"] for c in ANALYSES.get(analysis, ()) if c["role"] != "compute")
