# -*- coding: utf-8 -*-
"""Editorial catalog of each element's fields.

Generated from the curation that used to be embedded in app.js's FormTemplates:
field order, label, and what counts as basic or advanced. That is engineering
judgement and does not derive from introspection -- which is why it lives here.

What is NOT here, because domain/schema.py derives it at runtime:
  - whether the parameter exists, and its default -> inspect.signature of the ROSS class
  - the help text                                 -> the class's numpydoc docstring
  - the unit and its alternatives                 -> domain/units.py
"""


def F(
    name,
    label_en,
    label_pt,
    group="main",
    section=None,
    control="text",
    options=None,
    optional=False,
    placeholder=None,
    is_dict=False,
):
    """Describe one form field."""
    return {
        "name": name,
        "label": {"en": label_en, "pt": label_pt},
        "group": group,
        "section": section,
        "control": control,
        "options": options,
        "optional": optional,
        "placeholder": placeholder,
        "is_dict": is_dict,
    }


SECTIONS = {
    "Mesh & Solver": {"en": "Mesh & Solver", "pt": "Malha e Solver"},
    "Loads & Positions": {"en": "Loads & Positions", "pt": "Cargas e Posições"},
    "Thermal Parameters": {"en": "Thermal Parameters", "pt": "Parâmetros Térmicos"},
}


FIELDS = {
    "materials": {
        "BASIC": [
            F("name", "Material Name", "Material"),
            F("rho", "Density", "Densidade"),
            F("E", "Elastic Modulus", "Módulo de Elasticidade", optional=True),
            F("G_s", "Shear Modulus", "Módulo de Cisalhamento", optional=True),
            F("poisson", "Poisson's Ratio", "Coeficiente de Poisson", optional=True),
            F("specific_heat", "Specific Heat", "Calor Específico", group="advanced"),
            F(
                "thermal_conductivity",
                "Thermal Conductivity",
                "Condutividade Térmica",
                group="advanced",
            ),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
    },
    "shafts": {
        "BASIC": [
            F("n", "Node #", "Nó", optional=True),
            F("L", "Length", "Comprimento"),
            F("odl", "Left Outer Diam", "Diâm. Externo Esq."),
            F("idl", "Left Inner Diam", "Diâm. Interno Esq."),
            F("material", "Material Name", "Material", control="material_ref"),
            F("odr", "Right Outer Diam", "Diâm. Externo Dir.", group="advanced"),
            F("idr", "Right Inner Diam", "Diâm. Interno Dir.", group="advanced"),
            F("axial_force", "Axial Force", "Força Axial", group="advanced"),
            F("torque", "Torque", "Torque", group="advanced"),
            F(
                "shear_effects",
                "Shear Effects",
                "Efeitos de Cisalhamento",
                group="advanced",
            ),
            F("rotary_inertia", "Rotary Inertia", "Inércia Rotativa", group="advanced"),
            F(
                "gyroscopic",
                "Gyroscopic Effect",
                "Efeito Giroscópico",
                group="advanced",
            ),
            F(
                "shear_method_calc",
                "Shear Calc Method",
                "Método de Cálculo do Cisalhamento",
                group="advanced",
            ),
            F("alpha", "Alpha", "Alfa", group="advanced"),
            F("beta", "Beta", "Beta", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
        ],
    },
    "disks": {
        "BASIC": [
            F("n", "Node #", "Nó", optional=True),
            F("m", "Mass", "Massa"),
            F("Ip", "Polar Inertia", "Inércia Polar"),
            F("Id", "Diametral Inertia", "Inércia Diametral"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
    },
    "gears": {
        "BASIC": [
            F("n", "Node #", "Nó", optional=True),
            F("m", "Mass", "Massa"),
            F("Ip", "Polar Inertia", "Inércia Polar"),
            F("Id", "Diametral Inertia", "Inércia Diametral"),
            F("n_teeth", "Number of Teeth", "Número de Dentes"),
            F("pitch_diameter", "Pitch Diameter", "Diâmetro Primitivo", optional=True),
            F("base_diameter", "Base Diameter", "Diâmetro de Base", optional=True),
            F("pr_angle", "Pressure Angle", "Ângulo de Pressão", group="advanced"),
            F("helix_angle", "Helix Angle", "Ângulo de Hélice", group="advanced"),
            F("bore_diameter", "Bore Diameter", "Diâmetro do Furo", group="advanced"),
            F(
                "material",
                "Material Name",
                "Material",
                group="advanced",
                control="material_ref",
            ),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "TVMS": [
            F("n", "Node #", "Nó", optional=True),
            F("material", "Material Name", "Material", control="material_ref"),
            F("width", "Tooth Width", "Largura do Dente"),
            F("bore_diameter", "Bore Diameter", "Diâmetro do Furo"),
            F("module", "Module", "Módulo"),
            F("n_teeth", "Number of Teeth", "Número de Dentes"),
            F("pr_angle", "Pressure Angle", "Ângulo de Pressão", group="advanced"),
            F("helix_angle", "Helix Angle", "Ângulo de Hélice", group="advanced"),
            F(
                "addendum_coeff",
                "Addendum Coefficient",
                "Coeficiente de Addendum",
                group="advanced",
            ),
            F(
                "tip_clearance_coeff",
                "Tip Clearance Coefficient",
                "Coef. de Folga de Topo",
                group="advanced",
            ),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
    },
    "bearings": {
        "BASIC": [
            F("n", "Node #", "Nó", optional=True),
            F("kxx", "kxx", "kxx"),
            F("cxx", "cxx", "cxx"),
            F("kxy", "kxy", "kxy", group="advanced"),
            F("kyx", "kyx", "kyx", group="advanced"),
            F("kyy", "kyy", "kyy", group="advanced"),
            F("cxy", "cxy", "cxy", group="advanced"),
            F("cyx", "cyx", "cyx", group="advanced"),
            F("cyy", "cyy", "cyy", group="advanced"),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("frequency", "Frequency", "Frequência", group="advanced"),
            F("mxx", "mxx", "mxx", group="advanced"),
            F("mxy", "mxy", "mxy", group="advanced"),
            F("myx", "myx", "myx", group="advanced"),
            F("myy", "myy", "myy", group="advanced"),
            F("kzz", "kzz", "kzz", group="advanced"),
            F("czz", "czz", "czz", group="advanced"),
            F("mzz", "mzz", "mzz", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "BallBearing": [
            F("n", "Node #", "Nó", optional=True),
            F("n_balls", "Number of Balls", "Número de Esferas"),
            F("d_balls", "Ball Diameter", "Diâmetro das Esferas"),
            F("fs", "Static Force", "Força Estática"),
            F("alpha", "Contact Angle", "Ângulo de Contato"),
            F("cxx", "cxx", "cxx", group="advanced"),
            F("cyy", "cyy", "cyy", group="advanced"),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "RollerBearing": [
            F("n", "Node #", "Nó", optional=True),
            F("n_rollers", "Number of Rollers", "Número de Roletes"),
            F("l_rollers", "Roller Length", "Comprimento dos Roletes"),
            F("fs", "Static Force", "Força Estática"),
            F("alpha", "Contact Angle", "Ângulo de Contato"),
            F("cxx", "cxx", "cxx", group="advanced"),
            F("cyy", "cyy", "cyy", group="advanced"),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "MagneticBearing": [
            F("n", "Node #", "Nó", optional=True),
            F("g0", "Nominal Air Gap", "Entreferro Nominal"),
            F("i0", "Bias Current", "Corrente de Polarização"),
            F("ag", "Effective Pole Area", "Área Efetiva do Polo"),
            F("nw", "Turns per Coil", "Espiras por Bobina"),
            F("kp_pid", "PID P Gain", "Ganho P do PID"),
            F("ki_pid", "PID I Gain", "Ganho I do PID"),
            F("kd_pid", "PID D Gain", "Ganho D do PID"),
            F("frequency", "Frequency", "Frequência", group="advanced"),
            F("alpha", "Pole Angular Pos", "Posição Angular do Polo", group="advanced"),
            F("k_amp", "Amp Gain", "Ganho do Amplificador", group="advanced"),
            F("k_sense", "Sensor Gain", "Ganho do Sensor", group="advanced"),
            F("n_f", "Cutoff Freq", "Frequência de Corte", group="advanced"),
            F(
                "sensors_axis_rotation",
                "Sensor Rotation Axis",
                "Eixo de Rotação do Sensor",
                group="advanced",
            ),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "Cylindrical": [
            F("n", "Node #", "Nó", optional=True),
            F("speed", "Frequencies", "Frequências"),
            F("weight", "Gravity Load", "Carga Gravitacional"),
            F("bearing_length", "Bearing Length", "Comprimento do Mancal"),
            F("journal_diameter", "Journal Diameter", "Diâmetro do Munhão"),
            F("radial_clearance", "Radial Clearance", "Folga Radial"),
            F("oil_viscosity", "Oil Viscosity", "Viscosidade do Óleo"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "PlainJournal": [
            F("n", "Node #", "Nó", optional=True),
            F("pad_axial_length", "Axial Length", "Comprimento Axial"),
            F("journal_diameter", "Journal Diameter", "Diâmetro do Munhão"),
            F("radial_clearance", "Radial Clearance", "Folga Radial"),
            F("n_pads", "Number of Pads", "Número de Sapatas"),
            F("pad_arc", "Pad Arc", "Arco da Sapata"),
            F("preload", "Preload", "Pré-carga"),
            F("oil_supply_temperature", "Oil Supply Temp", "Temp. de Alimentação"),
            F("frequency", "Frequency", "Frequência"),
            F("fxs_load", "FXS Load", "Carga FXS"),
            F("fys_load", "FYS Load", "Carga FYS"),
            F("lubricant", "Lubricant", "Lubrificante"),
            F("initial_position", "Initial Position (x,y)", "Posição Inicial (x,y)"),
            F("oil_supply_pressure", "Oil Supply Pres", "Pressão de Alimentação"),
            F("oil_flow_v", "Oil Flow (v)", "Vazão de Óleo (v)"),
            F("pad_thickness", "Pad Thickness", "Espessura da Sapata"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "SqueezeFilm": [
            F("n", "Node #", "Nó", optional=True),
            F("frequency", "Frequencies", "Frequências"),
            F("axial_length", "Axial Length", "Comprimento Axial"),
            F("journal_diameter", "Journal Diameter", "Diâmetro do Munhão"),
            F("radial_clearance", "Radial Clearance", "Folga Radial"),
            F("eccentricity_ratio", "Eccentricity Ratio", "Razão de Excentricidade"),
            F("lubricant", "Lubricant", "Lubrificante"),
            F(
                "geometry",
                "Geometry",
                "Geometria",
                group="advanced",
                placeholder="groove",
            ),
            F("cavitation", "Cavitation (True/False)", "Cavitação", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
        ],
        "ThrustPad": [
            F("n", "Node #", "Nó", optional=True),
            F("pad_inner_radius", "Pad Inner Radius", "Raio Interno da Sapata"),
            F("pad_outer_radius", "Pad Outer Radius", "Raio Externo da Sapata"),
            F("pad_pivot_radius", "Pad Pivot Radius", "Raio do Pivô da Sapata"),
            F("pad_arc", "Pad Arc", "Arco da Sapata"),
            F("pivot_angle", "Pivot Angle", "Ângulo do Pivô"),
            F("oil_supply_temperature", "Oil Supply Temp", "Temp. de Alimentação"),
            F("lubricant", "Lubricant", "Lubrificante"),
            F("n_pads", "Number of Pads", "Número de Sapatas"),
            F("n_theta", "Theta Mesh (n_theta)", "Malha em Theta (n_theta)"),
            F("n_radial", "Radial Mesh (n_radial)", "Malha Radial (n_radial)"),
            F("frequency", "Frequencies", "Frequências"),
            F("equilibrium_position_mode", "Equilibrium Mode", "Modo de Equilíbrio"),
            F("radial_inclination_angle", "Radial Inclination", "Inclinação Radial"),
            F(
                "circumferential_inclination_angle",
                "Circumferential Inclination",
                "Inclinação Circunferencial",
            ),
            F(
                "initial_film_thickness",
                "Initial Film Thickness",
                "Espessura Inicial do Filme",
            ),
            F("model_type", "Model type", "Tipo de Modelo", group="advanced"),
            F(
                "tolerance_force_moment",
                "Force/Moment Tolerance",
                "Tolerância de Força/Momento",
                group="advanced",
            ),
            F(
                "residual_force_moment",
                "Initial Residual",
                "Resíduo Inicial",
                group="advanced",
            ),
            F("axial_load", "Axial Load", "Carga Axial", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "TiltingPad": [
            F("n", "Node #", "Nó", optional=True),
            F("journal_diameter", "Journal Diameter", "Diâmetro do Munhão"),
            F("pad_axial_length", "Pad Axial Length", "Comprimento Axial da Sapata"),
            F("radial_clearance", "Radial Clearance", "Folga Radial"),
            F("pad_thickness", "Pad Thickness", "Espessura da Sapata"),
            F("pad_arc", "Pad Arc", "Arco da Sapata"),
            F("pivot_angle", "Pivot Angle", "Ângulo do Pivô"),
            F("preload", "Preload", "Pré-carga"),
            F("offset", "Offset", "Offset"),
            F("lubricant", "Lubricant", "Lubrificante"),
            F("oil_supply_temperature", "Oil Supply Temp", "Temp. de Alimentação"),
            F("frequency", "Frequency", "Frequência"),
            F(
                "total_ex_film",
                "Total EX Film",
                "Total EX do Filme",
                section="Mesh & Solver",
            ),
            F(
                "total_ez_film",
                "Total EZ Film",
                "Total EZ do Filme",
                section="Mesh & Solver",
            ),
            F(
                "total_ey_pad",
                "Total EY Pad",
                "Total EY da Sapata",
                section="Mesh & Solver",
            ),
            F(
                "equilibrium_type",
                "Equilibrium Type",
                "Tipo de Equilíbrio",
                section="Mesh & Solver",
            ),
            F(
                "eccentricity",
                "Eccentricity",
                "Excentricidade",
                section="Mesh & Solver",
            ),
            F(
                "attitude_angle",
                "Attitude Angle",
                "Ângulo de Atitude",
                section="Mesh & Solver",
            ),
            F("fxs_load", "FXS Load", "Carga FXS", section="Loads & Positions"),
            F("fys_load", "FYS Load", "Carga FYS", section="Loads & Positions"),
            F("xj", "xj Position", "Posição xj", section="Loads & Positions"),
            F("yj", "yj Position", "Posição yj", section="Loads & Positions"),
            F(
                "thermal_type",
                "Thermal Type",
                "Tipo Térmico",
                section="Thermal Parameters",
            ),
            F(
                "pad_conductivity",
                "Pad Conductivity",
                "Condutividade da Sapata",
                section="Thermal Parameters",
            ),
            F(
                "edges_convection",
                "Edges Convection",
                "Convecção nas Bordas",
                section="Thermal Parameters",
            ),
            F(
                "relax_temperature",
                "Relax Temperature",
                "Relaxação de Temperatura",
                section="Thermal Parameters",
            ),
            F(
                "journal_temperature",
                "Journal Temp",
                "Temp. do Munhão",
                section="Thermal Parameters",
            ),
            F(
                "oil_flow_v",
                "Oil Flow (v)",
                "Vazão de Óleo (v)",
                section="Thermal Parameters",
            ),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
    },
    "seals": {
        "BASIC": [
            F("n", "Node #", "Nó", optional=True),
            F("kxx", "kxx", "kxx"),
            F("cxx", "cxx", "cxx"),
            F("seal_leakage", "Seal Leakage", "Vazamento do Selo", group="advanced"),
            F("kxy", "kxy", "kxy", group="advanced"),
            F("kyx", "kyx", "kyx", group="advanced"),
            F("kyy", "kyy", "kyy", group="advanced"),
            F("cxy", "cxy", "cxy", group="advanced"),
            F("cyx", "cyx", "cyx", group="advanced"),
            F("cyy", "cyy", "cyy", group="advanced"),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("frequency", "Frequency", "Frequência", group="advanced"),
            F("mxx", "mxx", "mxx", group="advanced"),
            F("mxy", "mxy", "mxy", group="advanced"),
            F("myx", "myx", "myx", group="advanced"),
            F("myy", "myy", "myy", group="advanced"),
            F("kzz", "kzz", "kzz", group="advanced"),
            F("czz", "czz", "czz", group="advanced"),
            F("mzz", "mzz", "mzz", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "HolePattern": [
            F("n", "Node #", "Nó", optional=True),
            F("shaft_diameter", "Shaft Diameter", "Diâmetro do Eixo"),
            F("radial_clearance", "Radial Clearance", "Folga Radial"),
            F("axial_length", "Axial Length", "Comprimento Axial"),
            F(
                "relative_roughness",
                "Relative Roughness (E/D)",
                "Rugosidade Relativa (E/D)",
            ),
            F("cell_length", "Cell Length", "Comprimento da Célula"),
            F("cell_width", "Cell Width", "Largura da Célula"),
            F("cell_depth", "Cell Depth", "Profundidade da Célula"),
            F("inlet_pressure", "Inlet Pressure", "Pressão de Entrada"),
            F("outlet_pressure", "Outlet Pressure", "Pressão de Saída"),
            F("inlet_temperature", "Inlet Temp", "Temp. de Entrada"),
            F("frequency", "Frequencies", "Frequências"),
            F("gas_composition", "Gas Composition", "Composição do Gás", is_dict=True),
            F("molar_mass", "Molar Mass", "Massa Molar", group="advanced"),
            F("gamma", "Gamma (Cp/Cv)", "Gama (Cp/Cv)", group="advanced"),
            F("sutherland_b", "Sutherland b", "Sutherland b", group="advanced"),
            F("sutherland_s", "Sutherland s", "Sutherland s", group="advanced"),
            F("preswirl", "Preswirl", "Pré-swirl", group="advanced"),
            F(
                "entrance_loss_coefficient",
                "Entrance Loss Coef",
                "Coef. de Perda na Entrada",
                group="advanced",
            ),
            F(
                "exit_loss_coefficient",
                "Exit Loss Coef",
                "Coef. de Perda na Saída",
                group="advanced",
            ),
            F(
                "excitation_ratio",
                "Excitation Ratio",
                "Razão de Excitação",
                group="advanced",
            ),
            F(
                "nz",
                "Axial Discretization nz",
                "Discretização Axial (nz)",
                group="advanced",
            ),
            F(
                "max_iterations",
                "Max Iterations",
                "Máx. de Iterações",
                group="advanced",
            ),
            F("tolerance", "Tolerance", "Tolerância", group="advanced"),
            F("first_step_size", "First Step Size", "Passo Inicial", group="advanced"),
            F(
                "relaxation_factor",
                "Relaxation Factor",
                "Fator de Relaxação",
                group="advanced",
            ),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "Labyrinth": [
            F("n", "Node #", "Nó", optional=True),
            F("shaft_diameter", "Shaft Diameter", "Diâmetro do Eixo"),
            F("radial_clearance", "Radial Clearance", "Folga Radial"),
            F("n_teeth", "Number of Teeth (<=30)", "Número de Dentes (≤30)"),
            F("pitch", "Seal Pitch", "Passo do Selo"),
            F("tooth_height", "Tooth Height", "Altura do Dente"),
            F("tooth_width", "Tooth Width", "Largura do Dente"),
            F(
                "seal_type",
                "Seal Type",
                "Tipo de Selo",
                control="select",
                options=["inter", "rotor", "stator"],
            ),
            F("inlet_pressure", "Inlet Pressure", "Pressão de Entrada"),
            F("outlet_pressure", "Outlet Pressure", "Pressão de Saída"),
            F("inlet_temperature", "Inlet Temp", "Temp. de Entrada"),
            F("frequency", "Frequency", "Frequência"),
            F("preswirl", "Preswirl", "Pré-swirl"),
            F("gas_composition", "Gas Composition", "Composição do Gás", is_dict=True),
            F("molar_mass", "Molar Mass", "Massa Molar", group="advanced"),
            F("gamma", "Gamma (Cp/Cv)", "Gama (Cp/Cv)", group="advanced"),
            F(
                "reference_temperatures",
                "Reference Temperatures",
                "Temperaturas de Referência",
                group="advanced",
            ),
            F(
                "reference_viscosities",
                "Reference Viscosities",
                "Viscosidades de Referência",
                group="advanced",
            ),
            F(
                "gas_model",
                "Gas Model",
                "Modelo de Gás",
                group="advanced",
                control="select",
                options=["ideal", "real"],
            ),
            F(
                "use_jenny_kanki",
                "Jenny & Kanki Swirl",
                "Swirl de Jenny & Kanki",
                group="advanced",
                control="select",
                options=["false", "true"],
            ),
            F(
                "print_results",
                "Print Results",
                "Imprimir Resultados",
                group="advanced",
                control="select",
                options=["false", "true"],
            ),
            F("n_link", "Link Node #", "Nó de Ligação", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
        "Hybrid": [
            F("n", "Node #", "Nó", optional=True),
            F("shaft_diameter", "Shaft Diameter", "Diâmetro do Eixo"),
            F("inlet_pressure", "Inlet Pressure", "Pressão de Entrada"),
            F("outlet_pressure", "Outlet Pressure", "Pressão de Saída"),
            F("inlet_temperature", "Inlet Temp", "Temp. de Entrada"),
            F("frequency", "Frequencies", "Frequências"),
            F(
                "hole_pattern_parameters",
                "Hole-Pattern Params",
                "Parâmetros Hole-Pattern",
                is_dict=True,
            ),
            F(
                "labyrinth_parameters",
                "Labyrinth Params",
                "Parâmetros do Labirinto",
                is_dict=True,
            ),
            F("gas_composition", "Gas Composition", "Composição do Gás", is_dict=True),
            F("molar_mass", "Molar Mass", "Massa Molar", group="advanced"),
            F("gamma", "Gamma (Cp/Cv)", "Gama (Cp/Cv)", group="advanced"),
            F("tolerance", "Tolerance", "Tolerância", group="advanced"),
            F(
                "max_iterations",
                "Max Iterations",
                "Máx. de Iterações",
                group="advanced",
            ),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
    },
    "couplings": {
        "BASIC": [
            F("n", "Node #", "Nó", optional=True),
            F("m_l", "m_l", "m_l"),
            F("m_r", "m_r", "m_r"),
            F("Ip_l", "Ip_l", "Ip_l"),
            F("Ip_r", "Ip_r", "Ip_r"),
            F("Id_l", "Id_l", "Id_l", group="advanced"),
            F("Id_r", "Id_r", "Id_r", group="advanced"),
            F("kt_x", "kt_x", "kt_x", group="advanced"),
            F("kt_y", "kt_y", "kt_y", group="advanced"),
            F("kt_z", "kt_z", "kt_z", group="advanced"),
            F("ct_x", "ct_x", "ct_x", group="advanced"),
            F("ct_y", "ct_y", "ct_y", group="advanced"),
            F("ct_z", "ct_z", "ct_z", group="advanced"),
            F("kr_x", "kr_x", "kr_x", group="advanced"),
            F("kr_y", "kr_y", "kr_y", group="advanced"),
            F("kr_z", "kr_z", "kr_z", group="advanced"),
            F("cr_x", "cr_x", "cr_x", group="advanced"),
            F("cr_y", "cr_y", "cr_y", group="advanced"),
            F("cr_z", "cr_z", "cr_z", group="advanced"),
            F("o_d", "Outer Diameter", "Diâmetro Externo", group="advanced"),
            F("L", "Length", "Comprimento", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
    },
    "pointmasses": {
        "BASIC": [
            F("n", "Node #", "Nó", optional=True),
            F("m", "Mass", "Massa"),
            F("mx", "mx", "mx", group="advanced"),
            F("my", "my", "my", group="advanced"),
            F("mz", "mz", "mz", group="advanced"),
            F("scale_factor", "Scale Factor", "Fator de Escala", group="advanced"),
            F("tag", "Tag", "Identificador", group="advanced"),
            F("color", "Hex Color", "Cor (hex)", group="advanced"),
        ],
    },
}
