name: Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

    # Installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Running pytest
      - name: Test with pytest
        run: |
          pip install pytest
          pytest ross --cov=ross
      - name: Run Ruff 
        run: |
          ruff check ross
        if: success()
      - name: Coverage and Deployment
        run: codecov
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          

